require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# ✔ Required for RN 0.82.1
platform :ios, '16.0'

prepare_react_native_project!

# Firebase static frameworks
use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true

target 'PrathamEnterprise' do
  config = use_native_modules!

  # # Lottie
  # pod 'lottie-ios', 
  

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    # Xcode 16 + iOS 18 Fix
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
        config.build_settings['VALIDATE_WORKSPACE'] = 'YES'
      end
    end
  end
end
