export const LOGIN_ACTION = `LOGIN_ACTION`;
export const SIGNUP_ACTION = `SIGNUP_ACTION`;
export const VERIFY_EMAIL_ACTION = `VERIFY_EMAIL_ACTION`;
export const REQUEST_FORGET_PASSWORD_ACTION = `REQUEST_FORGET_PASSWORD_ACTION`;
export const VERIFY_FORGET_PASSWORD_OTP_ACTION = `VERIFY_FORGET_PASSWORD_OTP_ACTION`;
export const RESET_PASSWORD_ACTION = `RESET_PASSWORD_ACTION`;
export const GET_PROFILE = 'GET_PROFILE';
export const GET_BANNERS_ACTION = `GET_BANNERS_ACTION`;
export const GET_CATEGORIES_ACTION = `GET_CATEGORIES_ACTION`;
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const GET_PRODUCTS_BY_CATEGORY = 'GET_PRODUCTS_BY_CATEGORY';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const PLACE_ORDER = 'PLACE_ORDER';
export const GET_SEARCH = 'GET_SEARCH';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const GET_BANNER_PRODUCTS = 'GET_BANNER_PRODUCTS';
export const GET_BRANDS = 'GET_BRANDS';
export const GET_ORDERHISTORY = 'GET_ORDERHISTORY';
export const CANCEL_ORDER = 'CANCEL_ORDER';
export const TRACK_ORDER = 'TRACK_ORDER';
export const ADD_TO_CART = 'ADD_TO_CART';
export const GET_CART_ITEMS = 'GET_CART_ITEMS';
export const GET_CART_ITEMS_SUCCESS = 'GET_CART_ITEMS_SUCCESS';
export const GET_CART_ITEMS_FAILURE = 'GET_CART_ITEMS_FAILURE';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
export const CLEAR_CART = 'CLEAR_CART';
export const UPDATE_MULTIPLE_CART_ITEMS = 'UPDATE_MULTIPLE_CART_ITEMS';
export const SYNC_CART = 'SYNC_CART';
export const GET_POLICY = 'GET_POLICY';
export const GET_ACCOUNT_STATUS = 'GET_ACCOUNT_STATUS';
export const GET_NOTIFICATIONS_ACTION = 'GET_NOTIFICATIONS_ACTION'
export const MARK_NOTIFICATION_READ_ACTION = 'MARK_NOTIFICATION_READ_ACTION'
export const MARK_ALL_READ_ACTION = 'MARK_ALL_READ_ACTION'
export const DELETE_NOTIFICATION_ACTION = 'DELETE_NOTIFICATION_ACTION'




